apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  volumes:
  - name: firstpvc-vol
    persistentVolumeClaim:
      claimName: firstpvc
  containers:
  - name: web-container
    image: nginx
    volumeMounts:
    - mountPath: "/mnt"
      name: firstpvc-vol
